# Data Cleaning & Preparation

Objective:
Prepare the e-commerce dataset for analysis by handling missing values,
converting data types, removing duplicates, and creating derived features.

Analyst: Poorva B R
Date: 24-Sep-2026

In [1]:
import pandas as pd

customers = pd.read_csv('../data/olist_customers_dataset.csv')
orders = pd.read_csv('../data/olist_orders_dataset.csv')
order_items = pd.read_csv('../data/olist_order_items_dataset.csv')
products = pd.read_csv('../data/olist_products_dataset.csv')

sales_data = (
    order_items
    .merge(products, on='product_id', how='left')
    .merge(orders, on='order_id', how='left')
    .merge(customers, on='customer_id', how='left')
)

print(sales_data.shape)

(112650, 26)

In [2]:
sales_data.duplicated().sum()

np.int64(0)

In [3]:
date_cols = [
    'shipping_limit_date',
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for col in date_cols:
    sales_data[col] = pd.to_datetime(sales_data[col])

sales_data[date_cols].dtypes

shipping_limit_date              datetime64[us]
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [5]:
sales_data['product_category_name'] = sales_data['product_category_name'].fillna('Unknown')

sales_data['product_name_lenght'] = sales_data['product_name_lenght'].fillna(
    sales_data['product_name_lenght'].median()
)

sales_data['product_description_lenght'] = sales_data['product_description_lenght'].fillna(
    sales_data['product_description_lenght'].median()
)

sales_data['product_photos_qty'] = sales_data['product_photos_qty'].fillna(
    sales_data['product_photos_qty'].median()
)

In [6]:
sales_data['delivery_days'] = (
    sales_data['order_delivered_customer_date']
    - sales_data['order_purchase_timestamp']
).dt.days

sales_data['delivery_days'].describe()

count    110196.000000
mean         12.007723
std           9.451455
min           0.000000
25%           6.000000
50%          10.000000
75%          15.000000
max         209.000000
Name: delivery_days, dtype: float64

In [7]:
sales_data['order_year'] = sales_data['order_purchase_timestamp'].dt.year

sales_data['order_month'] = sales_data['order_purchase_timestamp'].dt.month

sales_data[['order_year', 'order_month']].head()

   order_year  order_month
0        2017            9
1        2017            4
2        2018            1
3        2018            8
4        2017            2

In [8]:
sales_data['total_revenue'] = (
    sales_data['price']
    + sales_data['freight_value']
)

sales_data[['price', 'freight_value', 'total_revenue']].head()

    price  freight_value  total_revenue
0   58.90          13.29          72.19
1  239.90          19.93         259.83
2  199.00          17.87         216.87
3   12.99          12.79          25.78
4  199.90          18.14         218.04

In [9]:
sales_data.shape

(112650, 30)